<script setup lang="ts">
import { computed,onMounted } from 'vue'
import { useDashboardStore } from '@/stores/dashboard'
import ApiState from '@/components/ui/ApiState.vue'
const store=useDashboardStore();const unlocked=computed(()=>store.achievements.filter(item=>Boolean(item.earned)))
onMounted(()=>store.fetchAchievements())
</script>
<template><ApiState :loading="store.loading" :error="store.error" :empty="!store.achievements.length" empty-text="Aún no hay logros configurados." @retry="store.fetchAchievements"><div class="achievements"><header><div><small>Tu camino</small><h1>{{unlocked.length}} de {{store.achievements.length}} logros</h1><p>Cada insignia refleja un paso real en tu proceso.</p></div><b>{{Math.round(unlocked.length/store.achievements.length*100)}}%</b></header><div class="grid"><article v-for="item in store.achievements" :key="item._id" :class="{locked:!item.earned}"><img v-if="item.icon?.deliveryUrl" :src="item.icon.deliveryUrl" alt=""><i v-else class="fa-solid fa-medal"/><h2>{{item.title}}</h2><p>{{item.description}}</p><small>{{item.earned?new Date(item.earned.awardedAt).toLocaleDateString('es-EC'):'Por desbloquear'}}</small></article></div></div></ApiState></template>
<style lang="scss" scoped>
.achievements{display:flex;flex-direction:column;gap:1.5rem}header{display:flex;justify-content:space-between;align-items:center;background:$lpb-white;border:1px solid var(--border);border-radius:1rem;padding:1.5rem}header small,article small{font:600 .65rem $font-mono;color:$lpb-green-deep;text-transform:uppercase}header h1{font:400 1.6rem $font-display;margin:.3rem 0}header p,article p{font:.85rem/1.5 $font-sans;color:$lpb-muted;margin:.3rem 0}header b{font:400 2rem $font-display;color:$lpb-green-deep}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}article{padding:1.4rem;border:1px solid rgba($lpb-green,.3);border-radius:1rem;background:$lpb-white}article i,article img{display:grid;place-items:center;width:54px;height:54px;border-radius:50%;background:rgba($lpb-green,.15);color:$lpb-green-deep;font-size:1.2rem;object-fit:cover}article h2{font:400 1.15rem $font-display;margin:1rem 0 .2rem}article.locked{opacity:.55;border-color:var(--border)}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.grid{grid-template-columns:1fr}}
</style>
