<script setup lang="ts">
import { onMounted,ref } from 'vue'
import { useDashboardStore } from '@/stores/dashboard'
import type { Recipe } from '@/types'
import ApiState from '@/components/ui/ApiState.vue'
const store=useDashboardStore();const selected=ref<Recipe|null>(null)
onMounted(()=>store.fetchRecipes())
</script>
<template><ApiState :loading="store.loading" :error="store.error" :empty="!store.recipes.length" empty-text="Aún no hay recetas publicadas." @retry="store.fetchRecipes"><div class="recipes">
  <div class="grid"><article v-for="recipe in store.recipes" :key="recipe._id" tabindex="0" @click="selected=recipe" @keydown.enter="selected=recipe"><div class="photo"><img v-if="recipe.cover?.deliveryUrl" :src="recipe.cover.deliveryUrl" :alt="recipe.title"></div><div class="body"><h2>{{recipe.title}}</h2><p>{{recipe.summary || recipe.description}}</p><span>{{recipe.prepMinutes + recipe.cookMinutes}} min · {{recipe.servings}} porciones</span></div></article></div>
  <Teleport to="body"><div v-if="selected" class="modal" @click.self="selected=null"><div class="panel"><button class="close" @click="selected=null">×</button><img v-if="selected.cover?.deliveryUrl" :src="selected.cover.deliveryUrl"><div class="content"><h2>{{selected.title}}</h2><p>{{selected.description}}</p><div class="columns"><section><h3>Ingredientes</h3><ul><li v-for="item in selected.ingredients" :key="item">{{item}}</li></ul></section><section><h3>Preparación</h3><ol><li v-for="item in selected.instructions" :key="item">{{item}}</li></ol></section></div></div></div></div></Teleport>
</div></ApiState></template>
<style lang="scss" scoped>
.recipes{display:flex;flex-direction:column;gap:1.25rem}.filters{display:flex;gap:.5rem;flex-wrap:wrap}.filters button{padding:.55rem .9rem;border:1px solid var(--border);border-radius:999px;background:$lpb-white;font:600 .68rem $font-mono;text-transform:uppercase}.filters .active{background:$lpb-black;color:$lpb-white}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.grid article{overflow:hidden;border:1px solid var(--border);border-radius:1rem;background:$lpb-white;cursor:pointer}.photo{aspect-ratio:4/3;background:rgba($lpb-green,.1)}.photo img{width:100%;height:100%;object-fit:cover}.body{padding:1rem}.body small,.content small{color:$lpb-green-deep;font:600 .65rem $font-mono;text-transform:uppercase}.body h2,.content h2{font:400 1.25rem $font-display;margin:.3rem 0}.body p,.content p,.columns{color:$lpb-muted;font:.85rem/1.5 $font-sans}.body span{font:.68rem $font-mono;color:$lpb-muted}.modal{position:fixed;inset:0;z-index:3000;background:rgba($lpb-black,.6);display:grid;place-items:center;padding:1rem}.panel{position:relative;max-width:760px;width:100%;max-height:90vh;overflow:auto;border-radius:1rem;background:$lpb-white}.panel>img{width:100%;max-height:320px;object-fit:cover}.content{padding:1.5rem}.close{position:absolute;right:1rem;top:1rem;width:38px;height:38px;border-radius:50%;background:$lpb-white;font-size:1.5rem}.columns{display:grid;grid-template-columns:1fr 1fr;gap:1.5rem}.columns h3{color:$lpb-black;font:400 1.1rem $font-display}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.grid,.columns{grid-template-columns:1fr}}
</style>
